---
- name:
  shell: tmsh mv cm device bigip1 {{hostname}}
- name:  rest self trust-domain
  shell: tmsh delete cm trust-domain Root
- name:  config devie self ha initialization ip infomation
  shell: tmsh modify /cm device {{hostname}} configsync-ip {{vlan_ha_selfip}} unicast-address { { ip {{vlan_ha_selfip}} } } mirror-ip {{vlan_ha_selfip}}
- name: set register args
  shell: tmsh list /sys global-settings hostname
  register: result
- debug:
    var: result.stdout_lines[1]
- name: bigip_a add bigip_b in trust domain
  shell: tmsh run /cm add-to-trust Root USername admin password admin device 1.1.1.2 device-name bigip_b.ansible.com
  when: result.stdout_lines[1] == '    hostname bigip_a.ansible.com'
- name: create sync-group device group
  shell: tmsh create /cm device-group my_device_group { devices add { bigip_a.ansible.com { } bigip_b.ansible.com { } } type sync-failover }
  when: result.stdout_lines[1] == '    hostname bigip_a.ansible.com'
- name: bigip_a sync to group K63470472
#  shell: tmsh run /cm config-sync to-group my_device_group
  shell: tmsh run cm config-sync force-full-load-push to-group my_device_group
  when: result.stdout_lines[1] == '    hostname bigip_a.ansible.com'
- name: SAVE----CONFIG
  shell: tmsh save /sys config partitions all